# Generated by Django 6.0.2 on 2026-02-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='club_logos/')),
                ('abbreviation', models.CharField(blank=True, max_length=5)),
                ('website', models.URLField(blank=True)),
            ],
        ),
    ]
