# Generated by Django 6.0.2 on 2026-02-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regattas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='club_logos/'),
        ),
    ]
