# Generated by Django 6.0.2 on 2026-02-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regattas', '0002_alter_club_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regatta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='regatta_logos/')),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
