# Generated by Django 6.0.2 on 2026-02-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regattas', '0003_regatta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regatta',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='regatta',
            old_name='location',
            new_name='venue',
        ),
        migrations.AddField(
            model_name='regatta',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='regatta',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
    ]
