# Generated by Django 6.0.2 on 2026-02-11 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regattas', '0004_alter_regatta_options_rename_location_regatta_venue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_category', models.CharField(choices=[('junior', 'U14'), ('senior', 'U16/Open'), ('masters', 'Masters'), ('lightweight', 'Lightweight')], max_length=20)),
                ('boat_class', models.CharField(choices=[('single', 'Single'), ('pair', 'Pair'), ('four', 'Four'), ('double', 'Double'), ('quadruple', 'Quadruple'), ('octuple', 'Octuple'), ('eight', 'Eight')], max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('race_number', models.IntegerField()),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('event_number', models.IntegerField()),
                ('regatta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regattas.regatta')),
            ],
        ),
    ]
